"""Story tags table

Revision ID: 056ca88b8731
Revises: 8b30cc3f7824
Create Date: 2025-12-02 23:36:36.126915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056ca88b8731'
down_revision: Union[str, None] = '8b30cc3f7824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tags_table = op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.bulk_insert(tags_table, [{'tag': 'Fantasy'}, {'tag': 'Romance'}, {'tag': 'Mystery'}])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
