# Successful registration
POST http://localhost:8000/users/register 
Content-Type: application/json

{
    "id": null,
    "username": "testUser1",
    "email": "testUser1@gmail.com",
    "password": "Testuser1@"
}

# Email invalid

# POST http://localhost:8000/users/register 

# {
#     "id": null,
#     "username": "testUser2",
#     "email": "testUser2gmail.com",
#     "password": "Testuser2@"
# }

# Email exists

# POST http://localhost:8000/users/register 

# {
#     "id": null,
#     "username": "testUser2",
#     "email": "testUser1@gmail.com",
#     "password": "Testuser1@"
# }

# Username Exists
# POST http://localhost:8000/users/register 

# {
#     "id": null,
#     "username": "testUser1",
#     "email": "testUser2@gmail.com",
#     "password": "Testuser2@"
# }

# Invalid password
# POST http://localhost:8000/users/register 

# {
#     "id": null,
#     "username": "testUser2",
#     "email": "testUser2@gmail.com",
#     "password": "Testuser2"
# }